name:                mut-stack
version:             0.1.0.0
github:              "githubuser/mut-stack"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/mut-stack#readme>

dependencies:
- base >= 4.7 && < 5

ghc-options:
- -Wall
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  mut-stack-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    dependencies:
    - mut-stack

tests:
  mut-stack-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mut-stack
    - HUnit >= 1.6 && < 1.7
