# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages (or just build if not pushing to `main`)

on:
  # Runs on pushes targeting the default branch
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]
    paths:
      - '**.hs'
      - 'mut.cabal'
      - '.github/workflows/**/*.yml'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  MAIN_PUSH: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
  PULL_REQUEST: ${{ github.event_name == 'pull_request' }}

permissions: write-all

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  build:
    runs-on: ubuntu-latest
    steps:
      - name: What is this?
        run: |
          echo "Action: ${{ github.event_name }}, ref: ${{ github.ref }}"
          echo "Main push: ${{ env.MAIN_PUSH }}"
          echo "Pull request: ${{ env.PULL_REQUEST }}"
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test it
        run: stack test
      - name: Run it
        run: stack run
      - name: Build docs
        # run: stack haddock --haddock-arguments="-o ./docs" 2&>docdir.txt
        run: ./bin/docs.sh
      - name: If PR, add comment
        if: ${{ env.PULL_REQUEST == 'true' }}
        run: |
          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            /repos/${{ github.event.pull_request.head.repo.owner.login }}/${{ github.event.pull_request.head.repo.name }}/issues/${{ github.event.pull_request.number }}/comments \
            -f body="$(cat ./output.md)"
      - name: If push to main, put file in branch
        if: ${{ env.MAIN_PUSH == 'true' }}
        run: |
          git fetch
          git rm -rf ./**/* --cached
          mv output.md README.md
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add README.md
          git comm "Deploy"
          git push origin output/built --force
      - name: Prep Pages
        if: ${{ env.MAIN_PUSH == 'true' }}
        uses: actions/configure-pages@v2
      - name: Upload to Pages
        if: ${{ env.MAIN_PUSH == 'true' }}
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./docs
      - name: Deploy to Pages
        if: ${{ env.MAIN_PUSH == 'true' }}
        uses: actions/deploy-pages@v1
      