# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]
    paths:
      - '**.hs'
      - 'mut.cabal'
      - '.github/workflows/**/*.yml'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  CAN_DEPLOY: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  setup:
    runs-on: ubuntu-latest
    outputs:
      var1: ${{ steps.set-variable.outputs.test }}
    steps:
      - uses: actions/checkout@v2
      - name: Set test variable
        id: set-variable
        run: |
          echo ${{ env.CAN_DEPLOY }}
          if [ ${{ env.CAN_DEPLOY }}]; then
            echo "IS PUSH TO MAIN"
            echo "{test}={github-pages}" >> $GITHUB_STATE
          else
            echo "ISN'T PUSH TO MAIN"
            echo "{test}={something-else}" >> $GITHUB_STATE
          fi
        shell: bash
      - name: Read exported variable
        run: |
          echo "OUTPUT: ${{ steps.check.test-env.test }}"
  deploy:
    needs: [setup]
    strategy:
      fail-fast: true
      matrix:
        include:
          - os: ubuntu-latest
            ghc: '8.8'
            cabal: '3.2'
    environment:
      name: ${{ needs.setup.outputs.var1 }}
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: What's our env?
        run: echo ${{ needs.setup.outputs.var1}}
      - name: Checkout
        uses: actions/checkout@v3
      - uses: haskell/actions/setup@v2
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}
      - name: Build docs
        run: >
          ./bin/build-docs.sh | tee docdir.txt;
          echo "DOCDIR=$(dirname $(cat docdir.txt | tail -1))" >> $GITHUB_ENV;
      - name: Build the app
        run: cabal build
      - if: ${{ env.CAN_DEPLOY }}
        name: Setup Pages
        uses: actions/configure-pages@v2
      - if: ${{ env.CAN_DEPLOY }}
        name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload entire repository
          path: ${{ env.DOCDIR }}
      - if: ${{ env.CAN_DEPLOY }}
        name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
